### ISSUE TITLE
Status as json file?

### ISSUE THREAD

**Issue by fbartels** [IamTheFij/minitor-go#1]
Hi,

I found this project of yours yesterday while following a link to your Gitea installation and like it for its simplicity.

For my home network I have currently a small bash script that pings certain endpoints and that renders a basic overview in a tmux window. I always wanted to modernise it, but "real" monitoring solutions always feel quite heavy for home usage.

For quick visualization I decided to use Monitoror (already running on my Cloudron) and to gather data I have originally been tinkering with https://github.com/mmastrac/stylus. But ultimately I ended using stylus just for its internal status.json file (which as a bit of a weird syntax or array in array in array).

What I think would be quite useful for minitor would be a json export similar to the Prometheus one. Something where you can do a `.monitors.name` or similar.

**Comment by IamTheFij** [comment]
Hey! Thanks for the interest. I had exactly the same motivations when I created Minitor.

Minitor already exports Prometheus metrics via an HTTP endpoint. I'm not familiar with the Prometheus JSON exporting feature though. Do you have a link to that?

**Comment by fbartels** [comment]
Ah no, maybe what I wrote was confusing. My json idea has nothing to do with Prometheus, my idea was to (in addition to the Prometheus metrics endpount) publush the state, number of errors, etc also as a json file.

PS: I think I have seen a few .drone.yml files in your repo but I guess you are using their hosted service? I have made a small Cloudron app from the drone server component. Would you be interested?

**Comment by IamTheFij** [comment]
Ah. I see. That's a good idea. With some refactoring I could probably come up with a standardized interface for metrics and then initialize either a JSON metrics handler or a Prometheus metrics handler based on flag.

For Drone, I'm actually hosting an instance on one of my other VPS servers. I have one that I use for playing around with other services that I don't really need to tie into Cloudron. For example, Drone doesn't really need to tie into LDAP auth because it uses the auth from Gitea, which is already on LDAP. I also host my own Prometheus and Grafana server on my secondary VPS.

That said, I'd be happy to test out a Cloudron version!

**Comment by fbartels** [comment]
Yes, I see it more as "not having to care about ssl and backups" as to why it could be useful on cloudron.

Sent you and invite feedback would be awesome.

**Comment by IamTheFij** [comment]
Yea, on my other server I use [a Restic container](https://github.com/ViViDboarder/docker-restic-cron) for backups and Traefik for SSL, so it's pretty straightforward for me to spin up a new service there.

Would this utility help with getting JSON results from Minitor? https://github.com/prometheus/prom2json It looks like it will allow scraping of any Prometheus metrics and parsing it as JSON.

Adding additional metrics exporters isn't something that I'm opposed to, but this seems like a quick way to get what you're looking for.

**Comment by IamTheFij** [comment]
Since it's been a while I'm going to close this. Since there appears to be a way to turn the prom API into JSON, I'd rather not add more complexity to Minitor. On one hand, a JSON file as output would be simpler than a Prometheus exporter, but the exporter also serves as a way of health checking Minitor and adding additional ways of alerting, so it seems worth leaving in.

I could probably test and include an example usage of `prom2json` in a compose file, if that would be helpful for anyone.
